apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-container
  template:
    metadata:
      labels:
        app: client-container
    spec:
      containers:
      - name: client-container
        image: image_client:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources: 
          requests:
            cpu: "500m" 
            memory: "256Mi" 
          limits:
            cpu: "1000m" 
            memory: "512Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: client-container-service
spec:
  selector:
    app: client-container
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-container-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-container
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50